import { ThemeProvider } from '@/provider/theme-provider'
import type { Metadata } from 'next'
import './globals.css'
import { validateRequest } from '@/auth'
import AuthProvider from '@/provider/auth-provider'

export const metadata: Metadata = {
  title: 'Lucia auth library.',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { user } = await validateRequest()

  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider user={user}>
        <body className={'bg-background font-sans antialiased'}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  )
}
